function dfunSymdZ = dL12dZ(alpha0,beta0,tetta,X,Y,Z)
%DL12DZ
%    DFUNSYMDZ = DL12DZ(ALPHA0,BETA0,TETTA,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    12-Apr-2020 15:12:58

t3 = sin(beta0);
t4 = cos(tetta);
t5 = cos(alpha0);
t6 = cos(beta0);
t7 = sin(tetta);
t9 = X.*5.0e2;
t10 = t4.*t6.*3.0;
t11 = t3.*t5.*t7.*3.0;
t2 = t9+t10-t11;
t13 = Y.*5.0e2;
t14 = t3.*t4.*3.0;
t15 = t5.*t6.*t7.*3.0;
t8 = t13+t14+t15;
t12 = t2.^2;
t16 = t8.^2;
t17 = t12+t16;
t20 = sqrt(t17);
t18 = t20+3.0;
t22 = Z.*5.0e2;
t23 = sin(alpha0);
t24 = t7.*t23.*3.0;
t19 = t22+t24;
t21 = t18.^2;
t25 = t19.^2;
t26 = t21+t25;
t27 = 1.0./t26;
t28 = t20.*t27.*1.2e1;
t29 = Z.*5.0e5;
t30 = t7.*t23.*3.0e3;
t31 = t29+t30;
[t33, t32] = ellipke(t28);
t34 = 1.0./sqrt(t17);
t35 = 1.0./t26.^2;
t36 = 1.0./pi;
t37 = 1.0./t17;
t38 = t20.*t27.*6.0;
t39 = t38-1.0;
t40 = t5.*3.0;
t41 = Y.*t6.*t7.*5.0e2;
t42 = X.*t4.*t5.*t6.*5.0e2;
t43 = Y.*t3.*t4.*t5.*5.0e2;
t44 = t40+t41+t42+t43-X.*t3.*t7.*5.0e2;
dfunSymdZ = sqrt(t26).*t36.*t37.*t44.*(-t39.*((t27.*t31.*t33)./2.0+(t27.*t31.*t32)./(t28.*2.0-2.0))+t20.*t31.*t33.*t35.*6.0+t20.*t31.*t35.*((t26.*t32.*t34)./2.4e1-(t26.*t33.*t34)./2.4e1).*1.2e1).*3.771e-9-1.0./sqrt(t26).*t31.*t36.*t37.*t44.*(t32+t33.*t39).*1.8855e-9;
